config/routes.rb
Adresar::Application.routes.draw do
  get "home/index"

  resources :contacts

  resources :addresses

  resources :firms

  resources :tags

  root :to => 'home#index'
end

app/models/firm.rb
class Firm < ActiveRecord::Base
  validates :title, :presence => true, :uniqueness => true
  validates :ico,   :presence => true, :uniqueness => true

  has_many :addresses
  has_and_belongs_to_many :tags
  
  accepts_nested_attributes_for :tags, :allow_destroy => :true, :reject_if => proc { |attrs| attrs.all? { |k,v| v.blank? }}
  accepts_nested_attributes_for :addresses, :allow_destroy => :true, :reject_if => proc { |attrs| attrs.all? { |k,v| v.blank? }}
end

app/controllers/firms_controller.rb
class FirmsController < ApplicationController
  # GET /firms
  # GET /firms.json
  def index
    @firms = Firm.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @firms }
    end
  end

  # GET /firms/1
  # GET /firms/1.json
  def show
    @firm = Firm.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @firm }
    end
  end

  # GET /firms/new
  # GET /firms/new.json
  def new
    @firm = Firm.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @firm }
    end
  end

  # GET /firms/1/edit
  def edit
    @firm = Firm.find(params[:id])
  end

  # POST /firms
  # POST /firms.json
  def create
    tags = params[:firm].delete(:tags_attributes)
    delete_empty(params[:firm])
    @firm = Firm.new(params[:firm])
    append_tags(tags)

    respond_to do |format|
      if @firm.save
        format.html { redirect_to @firm, notice: 'Firm was successfully created.' }
        format.json { render json: @firm, status: :created, location: @firm }
      else
        format.html { render action: "new" }
        format.json { render json: @firm.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /firms/1
  # PUT /firms/1.json
  def update
    @firm = Firm.find(params[:id])
    delete_empty(params[:firm])
    append_tags(params[:firm].delete(:tags_attributes))

    respond_to do |format|
      if @firm.update_attributes(params[:firm])
        format.html { redirect_to @firm, notice: 'Firm was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @firm.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /firms/1
  # DELETE /firms/1.json
  def destroy
    @firm = Firm.find(params[:id])
    @firm.destroy

    respond_to do |format|
      format.html { redirect_to firms_url }
      format.json { head :no_content }
    end
  end

private

  # handle tags from form
  # make sure no duplicit tags are created or assigned
  def append_tags(tags)
    keys = tags.keys.sort
    new_tags = []
    keys.each do |k|
      next if tags[k]["name"].to_s.strip.empty?
      tag = Tag.find_or_create_by_name(tags[k]["name"])
      if tags[k]["_destroy"] == "1"
        @firm.tags.delete(tag)
      else
        new_tags << tag
      end
    end
    new_tags.each { |t| @firm.tags << t unless @firm.tags.include?(t) }
  end

  # delete recursively empty attributes from form
  # no empty contacts or addresses are created
  def delete_empty(hash)
    empty = true
    hash.each do |k, v|
      if v.kind_of?(Hash)
        vempty = delete_empty(v)
        empty = false unless vempty
        hash.delete(k) if vempty
      else
        empty = false unless v.empty?
      end
    end
    hash.clear if empty
    empty
  end

end

app/helpers/firms_helper.rb
module FirmsHelper
end

app/views/firms/_entry.html.erb
<div class="vcard">
  <div><b><%= t(:title) %>:</b> <span class="fn org"><%= link_to firm.title, firm %></span></div>
  <div><b><%= t(:web) %>:</b> <span class="url"><a href="<%= firm.web %>"><%= firm.web %></a></span></div>
  <div><b><%= t(:ico) %>:</b> <span class="uid"><%= firm.ico %></span></div>
  <div><b><%= t(:note) %>:</b> <span class="note"><%= firm.note %></span></div>
  <% firm.addresses.each do |address| %>
    <b><%= t(:address) %></b><br />
    <div class="adr">
      <div class="name"><%= address.name %></div>
      <div class="street-address"><%= address.street %></div>
      <div><span class="postal-code"><%= address.psc %></span>&nbsp;<span class="locality"><%= address.city %></span></div>
    </div>
    <% address.contacts.each do |contact| %>
      <b><%= t(:contact) %></b><br />
      <div class="contact">
        <div><span class="name"><%= contact.name %></span></div>
        <div><span class="email"><%= contact.email %></span></div>
        <% contact.phones.each do |phone| %>
          <div><span class="tel"><%= phone.format_number %></span></div>
        <% end %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/firms/_form.html.erb
<% @firm.tags.build %>
<% @firm.addresses.build %>
<%= form_for(@firm) do |f| %>
  <% if @firm.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@firm.errors.count, "error") %> prohibited this firm from being saved:</h2>

      <ul>
      <% @firm.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label t(:title) %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label t(:ico) %><br />
    <%= f.text_field :ico %>
  </div>
  <div class="field">
    <%= f.label t(:note) %><br />
    <%= f.text_field :note %>
  </div>
  <div class="field">
    <%= f.label t(:web) %><br />
    <%= f.text_field :web %>
  </div>

  <b><%= t(:tags) %></b>
  <%= render :partial => 'tags/form',
             :locals  => {:form => f} %>

  <%= render :partial => 'addresses/form',
             :locals  => {:form => f} %>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/firms/edit.html.erb
<h1><%= t(:edit_firm) %> <%= @firm.title %></h1>

<%= render 'form' %>

<%= link_to t(:show), @firm %> |
<%= link_to t(:back), firms_path %>

app/views/firms/index.html.erb
<h1><%= t(:address_book) %></h1>

<table>
  <tr>
    <th><%= t(:title) %></th>
    <th><%= t(:web) %></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @firms.each do |firm| %>
  <tr>
    <td><%= firm.title %></td>
    <td><%= firm.web %></td>
    <td><%= link_to t(:show), firm %></td>
    <td><%= link_to t(:edit), edit_firm_path(firm) %></td>
    <td><%= link_to t(:destroy), firm, confirm: t(:confirm), method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to t(:new_firm), new_firm_path %>

app/views/firms/new.html.erb
<h1><%= t(:new_firm) %></h1>

<%= render 'form' %>

<%= link_to t(:back), firms_path %>

app/views/firms/show.html.erb
<%= render :partial => 'entry', :locals => {:firm => @firm} %>

<div>
  <b><%= t(:tags) %></b>
  <% @firm.tags.each do |tag| %>
    <%= link_to tag.name, tag %>
  <% end %>
</div>
<br />
<div>
  <%= link_to t(:edit), edit_firm_path(@firm) %>
  <%= link_to t(:destroy), @firm, confirm: t(:confirm), method: :delete %>
</div>