config/routes.rb
Adresar::Application.routes.draw do
  get "home/index"

  resources :contacts

  resources :addresses

  resources :firms

  resources :tags

  root :to => 'home#index'
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  # GET /addresses
  # GET /addresses.json
  def index
    @addresses = Address.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @addresses }
    end
  end

  # GET /addresses/1
  # GET /addresses/1.json
  def show
    @address = Address.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @address }
    end
  end

  # GET /addresses/new
  # GET /addresses/new.json
  def new
    @address = Address.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @address }
    end
  end

  # GET /addresses/1/edit
  def edit
    @address = Address.find(params[:id])
  end

  # POST /addresses
  # POST /addresses.json
  def create
    @address = Address.new(params[:address])

    respond_to do |format|
      if @address.save
        format.html { redirect_to @address, notice: 'Address was successfully created.' }
        format.json { render json: @address, status: :created, location: @address }
      else
        format.html { render action: "new" }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /addresses/1
  # PUT /addresses/1.json
  def update
    @address = Address.find(params[:id])

    respond_to do |format|
      if @address.update_attributes(params[:address])
        format.html { redirect_to @address, notice: 'Address was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /addresses/1
  # DELETE /addresses/1.json
  def destroy
    @address = Address.find(params[:id])
    @address.destroy

    respond_to do |format|
      format.html { redirect_to addresses_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/views/addresses/_form.html.erb
<%= form.fields_for :addresses do |f| %>

  <b><%= t(:address) %></b>
  <% unless f.object.nil? || f.object.new_record? %>
    <span class="field">
      <%= f.check_box :_destroy %>
      <%= f.label :_destroy, t(:remove) %>
    </span>
  <% end %>

<div class="address">

  <div class="field">
    <%= f.label t(:name) %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label t(:street) %><br />
    <%= f.text_field :street %>
  </div>
  <div class="field">
    <%= f.label t(:city) %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label t(:psc) %><br />
    <%= f.text_field :psc %>
  </div>

  <div class="contacts">
  <% f.object.contacts.build if f.object %>
  <%= render :partial => 'contacts/form',
             :locals  => {:form => f} %>
  </div>

</div>

<% end %>

app/views/addresses/edit.html.erb
<h1>Editing address</h1>

<%= render 'form' %>

<%= link_to t(:show), @address %> |
<%= link_to t(:back), addresses_path %>

app/views/addresses/index.html.erb
<h1>Listing addresses</h1>

<table>
  <tr>
    <th><%= t(:city) %></th>
    <th><%= t(:street) %></th>
    <th><%= t(:psc) %></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @addresses.each do |address| %>
  <tr>
    <td><%= address.city %></td>
    <td><%= address.street %></td>
    <td><%= address.psc %></td>
    <td><%= link_to t(:show), address %></td>
    <td><%= link_to t(:edit), edit_address_path(address) %></td>
    <td><%= link_to t(:destroy), address, confirm: t(:confirm), method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to t(:new_address), new_address_path %>

app/views/addresses/new.html.erb
<h1>New address</h1>

<%= render 'form' %>

<%= link_to 'Back', addresses_path %>

app/views/addresses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b><%= t(:city) %>:</b>
  <%= @address.city %>
</p>

<p>
  <b><%= t(:street) %>:</b>
  <%= @address.street %>
</p>

<p>
  <b><%= t(:psc) %>:</b>
  <%= @address.psc %>
</p>


<%= link_to t(:edit), edit_address_path(@address) %> |
<%= link_to t(:back), addresses_path %>